trafficviolationbackend/urls.py
from django.contrib import admin
from django.urls import include, path

from videoreport import views

urlpatterns = [
    path('', views.index, name="home"),
    path('videoreport/', views.get_report, name="videoreport"),
    path('download/', views.download, name="download"),
    #path('download_file/', views.download_file, name="download_file"),
    #path('/static/Violated_cars/violated_data.csv', views.download_file, name='download_file'),
    path('admin/', admin.site.urls),
]

videoreport/models.py
from django.db import models

# Create your models here.

videoreport/forms.py
from django import forms

class ReportForm(forms.Form):
    officer_name = forms.CharField(label='Officer name ',widget=forms.TextInput(attrs={'placeholder': 'in-charge of reporting official'}), max_length=100)
    red_duration = forms.IntegerField(label='Red Signal Duration ', widget=forms.TextInput(attrs={'placeholder': 'Red Signal Duration in seconds)'}), max_value=200)
    yellow_duration = forms.IntegerField(label='Yellow Signal Duration ', widget=forms.TextInput(attrs={'placeholder': 'Yellow Signal Duration in seconds)'}), max_value=50)
    green_duration = forms.IntegerField(label='Green Signal Duration ', widget=forms.TextInput(attrs={'placeholder': 'Green Signal Duration in seconds)'}), max_value=200)
    start_time = forms.IntegerField(label='Start Time ', widget=forms.TextInput(attrs={'placeholder': 'red signal starting on video'}),min_value=0, max_value=59)
    video_taken_time = forms.DateTimeField(label='Video captured at ', widget=forms.TextInput(attrs={'placeholder': 'dd/mm/yyyy hh:mm:ss'}))
    video = forms.FileField()
    position = forms.CharField(max_length=10, widget=forms.Select(choices=(('near', 'Near'),('medium','Medium'), ('far', 'Far') )))

videoreport/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage
import os
from .forms import ReportForm
from .backend import start_checking
#from django.utils.encoding import smart_str
import mimetypes

global csrf_temp_token
csrf_temp_token=["one"]

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

def get_report(request):
    context={}
    path = 'media/'
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        
        # create a form instance and populate it with data from the request:
        form = ReportForm(request.POST)
        # check whether it's valid:
        print(form.is_valid())
        print(request.FILES, "request file")
        #temp=str(type(request.FILES['document'])).lower()
        context['form']=form
        print(len(request.POST))
        print(request.POST)
        if "document" in request.FILES and csrf_temp_token[-1]!=request.POST['csrfmiddlewaretoken']:
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            csrf_temp_token.remove(csrf_temp_token[-1])
            csrf_temp_token.append(request.POST['csrfmiddlewaretoken'])
            uploaded_file = request.FILES['document']
            if uploaded_file.name.endswith(".avi") or uploaded_file.name.endswith(".mp4") or uploaded_file.name.endswith(".webm") or uploaded_file.name.endswith(".m4v"):
                fs = FileSystemStorage()
                remove_files(path)
                name = fs.save(uploaded_file.name, uploaded_file)
                context['upload']='YES'
                context['url'] = fs.url(name)
                context['message']='File Uploaded Successfully'
                #request.FILES=None
                video_path=path+uploaded_file.name
                red_start_time=request.POST['start_time']
                red_duration=request.POST['red_duration']
                green_duration=request.POST['green_duration']
                yellow_duration=request.POST['yellow_duration']
                date_time=request.POST['video_taken_time']
                stop_line_type=request.POST['position']
                start_checking(video_path, red_start_time, red_duration, green_duration, yellow_duration, date_time, stop_line_type)
                return render(request, 'download.html')
            else:
                context['message']='Upload a valid Video'
            return render(request, 'home.html', context)
            #return redirect('')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ReportForm()

    return render(request, 'home.html', {'form': form})
    
def remove_files(path):
    files_in_dir = os.listdir(path)
    for f in files_in_dir:
        os.remove(f'{path}{str(f)}')
        
def download(request):
    path='/static_files/Violated_cars/violated_data.csv'
    return render(request, 'download.html', {'url': path})
    
def download_file(request):
    fl_path = '/static/Violated_cars/'
    filename = 'violated_data.csv'
    fl = open(fl_path, 'r')
    mime_type, _ = mimetypes.guess_type(fl_path)
    response = HttpResponse(fl, content_type=mime_type)
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    return response

trafficviolationbackend/templates/base.html
{% load static %}<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>{% block title %}Traffic Violation Report{% endblock %}</title>
</head>
<body class="bg-transparent">
  <nav class="navbar navbar-expand-lg navbar-light mb-4 bg-warning">
    <div class="container d-inline-block text-center">
      <a class="navbar-brand" href="{% url 'home' %}">Traffic Violation Report App</a>
    </div>
  </nav>
  <div class="container">
    <div class="row justify-content-center p-lg-5 p-xs-0">
      <div class="col-lg-10 col-md-12 col-sm-12">
        <div class="card rounded-lg">
          <div class="card-body rounded shadow-lg bg-dark text-light">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

trafficviolationbackend/templates/download.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
<style>
.tab {
  overflow: hidden;
  border: 1px solid #ccc;
  background-color: #f1f1f1;
}
</style>

<div class="form-row mb-3 ">
    <div class="form-group col-md-4 col-sm-6 col-xs-12 mb-0">
		<a href="{% url 'videoreport' %}"><button class="btn btn-warning shadow" id="videoreport"> Video Report Page </button></a>
	</div>
	<div class="col-md-4 col-sm-6 col-xs-12">
			<a href="{% static "Violated_cars/violated_data.csv" %}" >
				<button type="submit" class="tab">Download Violated Data</button>
			</a>
    </div>
</div>

{% endblock %}

trafficviolationbackend/templates/home.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-row mb-3 ">
      <div class="form-group col-md-4 col-sm-6 col-xs-12 mb-0">
        {{ form.officer_name|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 col-sm-6 col-xs-12 mb-0">
        {{ form.start_time|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 col-sm-6 col-xs-12 mb-0">
        {{ form.video_taken_time|as_crispy_field }}
      </div>
    </div>
    <div class="form-row mb-3 ">
      <div class="form-group col-md-4 col-sm-6 col-xs-12 mb-0">
        {{ form.red_duration|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 col-sm-6 col-xs-12 mb-0">
        {{ form.yellow_duration|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 col-sm-6 col-xs-12 mb-0">
        {{ form.green_duration|as_crispy_field }}
      </div>
    </div>
    <div class="form-row mb-3 d-flex justify-content-center">
        <div class="col-md-4 col-sm-6 col-xs-12">
            {{ form.position|as_crispy_field }}
        </div>
        <div class="col-md-4 col-sm-6 col-xs-12">
            <tr>
				<th><label for="id_video">Video *</label></th>
				<td><input type="file" name="document" required id="id_video">{{message}}</td>
				</tr>
        </div>
    </div>
    <div class="d-flex justify-content-end">
        <button type="submit" class="btn btn-warning shadow">Upload and Process</button>
    </div>
</form>

{% endblock %}